### PR TITLE
[I4XGEK] Considering query restart also as restore

### PR DESCRIPTION
**Pull request by ikishore**
### What type of PR is this?

bug

### What does this PR do / why do we need it:

Considering query restart also as recovery and updating metrics accordingly

### Which issue(s) this PR fixes:

Fixes https://gitee.com/openlookeng/hetu-core/issues/I4XGEK

### Special notes for your reviewers:

### CODE REVIEW

**Comment by Nitin-Kashyap** [comment]
lgtm

**Comment by ikishore** [comment]
Messup because of rebase, will create new one

**Pull request closed without merging**
