### PR TITLE
Introducing failure retry policy profiles.

### PR DESCRIPTION
**Pull request by ahanapradhan**
### What type of PR is this?

/kind task 

### What does this PR do / why do we need it:

adding failure retry profiles.

etc/config.properties can have property fd.retry.profile=test (if this property is not specified, default profile is taken)

etc/failure-retry-policy/test.properties would contain all other parameters of the failure detection mechanism.

example:
fd.retry.type=timeout (or max-retry)
max.error.duration=60s (default is 300s)
max.retry.count=230 (default is 100) // this field is not used when fd.retry.type=timeout

default profile is timeout based.

### Which issue(s) this PR fixes:

Fixes #

### Special notes for your reviewers:

### CODE REVIEW

**Comment by Nitin-Kashyap** [comment]
lgtm

**Comment by ahanapradhan** [comment]
This PR has already been merged through Gitee PR https://gitee.com/openlookeng/hetu-core/pulls/1463

**Pull request closed without merging**
